services:
  directus:
    image: directus/directus:11.2.2
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      # Mount the extensions directory to make custom extensions available
      - ./myendpoint:/directus/extensions/directus-extension-myendpoint
      - ./myinterface:/directus/extensions/directus-extension-myinterface
      - ./myhook:/directus/extensions/directus-extension-myhook
      - ./mybundle:/directus/extensions/directus-extension-mybundle
      - ./myoperation:/directus/extensions/directus-extension-myoperation
    environment:
      SECRET: "replace-with-secure-random-value"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      WEBSOCKETS_ENABLED: "true"
      # Enable extension debugging if needed
      LOG_LEVEL: "debug"
      PUBLIC_URL: "http://localhost:8055"
      EXTENSIONS_PATH: "/directus/extensions"
      EXTENSIONS_AUTO_RELOAD: "true"